package main

import (
	"bufio"
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/GitRowin/orderedmapjson"
	"github.com/whacked/yamdb/pkg/codec"
	"github.com/whacked/yamdb/pkg/io/yamlutil"
	"gopkg.in/yaml.v3"
)

//go:embed examples
var examplesFS embed.FS

// ExampleEntry mirrors one entry in examples/index.json.
type ExampleEntry struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Input        string   `json:"input"`
	OutputFormat string   `json:"output_format"`
	Flags        []string `json:"flags"`
}

// ExamplesIndex mirrors the top-level structure of examples/index.json.
type ExamplesIndex struct {
	Version  int            `json:"version"`
	Examples []ExampleEntry `json:"examples"`
}

func loadExamplesIndex() (*ExamplesIndex, error) {
	data, err := examplesFS.ReadFile("examples/index.json")
	if err != nil {
		return nil, fmt.Errorf("reading embedded examples/index.json: %w", err)
	}
	var idx ExamplesIndex
	if err := json.Unmarshal(data, &idx); err != nil {
		return nil, fmt.Errorf("parsing examples/index.json: %w", err)
	}
	return &idx, nil
}

// expandSparseJSONLToString runs the carry-forward processor on sparse JSONL.
func expandSparseJSONLToString(data []byte) (string, error) {
	processor := codec.NewJSONLProcessor()
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		var node yaml.Node
		if err := yaml.Unmarshal([]byte(line), &node); err != nil {
			return "", fmt.Errorf("parsing JSONL line: %w", err)
		}
		record := orderedmapjson.NewAnyOrderedMap()
		if err := yamlutil.ConvertNodeToOrderedMap(&node, record); err != nil {
			return "", fmt.Errorf("converting to ordered map: %w", err)
		}
		if _, err := processor.ProcessRecord(record); err != nil {
			return "", fmt.Errorf("processing record: %w", err)
		}
	}
	return processor.ToExpandedJSONL(true), nil
}

// runExample converts the embedded input of e and returns the output string.
func runExample(e ExampleEntry, inputContent []byte) (string, error) {
	// Reset codec globals to defaults before each example.
	codec.VerbosityLevel = 0
	codec.ArraySeparator = ", "
	codec.TimeColumns = nil
	codec.DataColumns = nil
	codec.JoinTableOrder = nil

	// Apply flags declared in the example.
	var exJoinTables string
	for i := 0; i < len(e.Flags); i++ {
		switch e.Flags[i] {
		case "-join-tables":
			if i+1 < len(e.Flags) {
				i++
				exJoinTables = e.Flags[i]
			}
		}
	}

	format := detectFormatFromExtension(e.Input)

	switch format {
	case "jsonl":
		if isSparseJSONL(string(inputContent)) {
			return expandSparseJSONLToString(inputContent)
		}
		if exJoinTables != "" {
			joinTablesMap := make(map[string]map[string]int)
			var order []string
			for _, field := range strings.Split(exJoinTables, ",") {
				field = strings.TrimSpace(field)
				if field != "" {
					joinTablesMap[field] = make(map[string]int)
					order = append(order, field)
				}
			}
			codec.JoinTableOrder = order
			return codec.JSONLToCPDWithJoinTables(strings.NewReader(string(inputContent)), joinTablesMap)
		}
		return codec.JSONLToCPD(strings.NewReader(string(inputContent)))
	case "yaml":
		return codec.CPDToJSONLUnified(strings.NewReader(string(inputContent)))
	default:
		return "", fmt.Errorf("unknown format for %s", e.Input)
	}
}

func printExamples() {
	printCUESchemaExamples()

	idx, err := loadExamplesIndex()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading examples: %v\n", err)
		os.Exit(1)
	}

	for _, ex := range idx.Examples {
		fmt.Printf("## %s\n\n", ex.Name)
		fmt.Printf("%s\n\n", ex.Description)

		inputData, err := examplesFS.ReadFile("examples/" + ex.Input)
		if err != nil {
			fmt.Printf("> error reading input: %v\n\n", err)
			continue
		}

		inputLabel := fmt.Sprintf("### Input (%s)", ex.Input)
		if len(ex.Flags) > 0 {
			inputLabel += fmt.Sprintf(" — flags: `%s`", strings.Join(ex.Flags, " "))
		}
		inputLang := langForFormat(detectFormatFromExtension(ex.Input))
		fmt.Printf("%s\n\n```%s\n%s```\n\n", inputLabel, inputLang, string(inputData))

		output, err := runExample(ex, inputData)
		if err != nil {
			fmt.Printf("> conversion error: %v\n\n", err)
			continue
		}

		cmd := fmt.Sprintf("cat %s | cpd", ex.Input)
		if len(ex.Flags) > 0 {
			cmd += " " + strings.Join(ex.Flags, " ")
		}
		outputLang := langForFormat(ex.OutputFormat)
		fmt.Printf("### Output (%s)\n\n`%s`\n\n```%s\n%s```\n\n", ex.OutputFormat, cmd, outputLang, output)
	}
}

func printGenDocs() {
	idx, err := loadExamplesIndex()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading examples: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("## Examples")
	fmt.Println()
	fmt.Println("<!-- generated by: cpd --gen-docs -->")
	fmt.Println()

	for _, ex := range idx.Examples {
		fmt.Printf("### %s\n\n", ex.Name)
		fmt.Printf("%s\n\n", ex.Description)

		inputData, err := examplesFS.ReadFile("examples/" + ex.Input)
		if err != nil {
			fmt.Printf("*Error reading input: %v*\n\n", err)
			continue
		}

		inputLang := langForFormat(detectFormatFromExtension(ex.Input))
		cliInvocation := "cpd " + ex.Input
		if len(ex.Flags) > 0 {
			cliInvocation += " " + strings.Join(ex.Flags, " ")
		}

		fmt.Printf("**Input** (`%s`):\n\n", cliInvocation)
		fmt.Printf("```%s\n%s```\n\n", inputLang, string(inputData))

		output, err := runExample(ex, inputData)
		if err != nil {
			fmt.Printf("*Conversion error: %v*\n\n", err)
			continue
		}

		outputLang := langForFormat(ex.OutputFormat)
		fmt.Printf("**Output** (`%s`):\n\n", ex.OutputFormat)
		fmt.Printf("```%s\n%s```\n\n", outputLang, output)
	}
}

func langForFormat(format string) string {
	switch format {
	case "yaml":
		return "yaml"
	case "jsonl":
		return "jsonl"
	case "json":
		return "json"
	default:
		return ""
	}
}
