// table.go
package types

import "fmt"

// SchemaVersion represents a version of the table schema
type SchemaVersion struct {
	Version int
	Columns []ColumnInfo
}

// TableEvolution tracks how a table's structure evolves over time
type TableEvolution struct {
	// Current schema version
	CurrentVersion int
	// Maps version number to schema definition
	SchemaVersions map[int]*SchemaVersion
	// Maps record index to the schema version it uses
	RecordVersionMap map[int]int
	// Maps user-supplied named fields to their position in the columns array
	FieldPositionMap map[string]int
}

// NewTableEvolution creates a new table evolution tracker
func NewTableEvolution() *TableEvolution {
	return &TableEvolution{
		CurrentVersion:   1,
		SchemaVersions:   make(map[int]*SchemaVersion),
		RecordVersionMap: make(map[int]int),
		FieldPositionMap: make(map[string]int),
	}
}

func promoteType(a, b ColumnType) ColumnType {
	if a == TypeString || b == TypeString {
		return TypeString
	}
	if a == TypeFloat || b == TypeFloat {
		return TypeFloat
	}
	return TypeInt
}

func fieldAlreadyMapped(autoField string, fmap map[string]string) bool {
	for _, v := range fmap {
		if v == autoField {
			return true
		}
	}
	return false
}

// applyFieldPositionMap rewrites column names according to the current FieldPositionMap
func (te *TableEvolution) applyFieldPositionMap(cols []ColumnInfo) []ColumnInfo {
	remapped := make([]ColumnInfo, len(cols))
	for i, col := range cols {
		if pos, ok := te.FieldPositionMap[col.Name]; ok {
			// If this is a named field, use its position to look up the actual field
			if pos < len(cols) {
				remapped[i] = ColumnInfo{
					Name:          cols[pos].Name,
					Type:          col.Type,
					AutoGenerated: false,
				}
			} else {
				remapped[i] = col
			}
		} else {
			remapped[i] = col
		}
	}
	return remapped
}

// UpdateColumns updates the current column structure based on new information
// Returns true if the structure changed
func (te *TableEvolution) UpdateColumns(newColumns []ColumnInfo) bool {
	changed := false

	// If we have no columns yet, just adopt the new ones
	if len(te.SchemaVersions) == 0 {
		te.SchemaVersions[1] = &SchemaVersion{
			Version: 1,
			Columns: newColumns,
		}
		return true
	}

	currentSchema := te.SchemaVersions[te.CurrentVersion]

	// Check if we need to create a new schema version
	needsNewVersion := false

	// First pass: check for incompatible changes and field supplantation
	for i, newCol := range newColumns {
		if !newCol.AutoGenerated {
			// If this is a named field, check if it maps to an existing position
			if existingPos, exists := te.FieldPositionMap[newCol.Name]; exists {
				if existingPos != i {
					needsNewVersion = true
					break
				}
			} else {
				// For any named field, map it to its current position
				te.FieldPositionMap[newCol.Name] = i
				needsNewVersion = true
			}
		}
	}

	if needsNewVersion {
		fmt.Printf("[DEBUG] FieldPositionMap: %+v\n", te.FieldPositionMap)
		te.CurrentVersion++

		// Create new schema with all columns from current schema
		newSchema := &SchemaVersion{
			Version: te.CurrentVersion,
			Columns: make([]ColumnInfo, len(currentSchema.Columns)),
		}

		// First, copy all existing columns
		copy(newSchema.Columns, currentSchema.Columns)

		// Create a new ordered slice for the final columns
		orderedColumns := make([]ColumnInfo, len(currentSchema.Columns))
		usedPositions := make(map[int]bool)

		// First, place all named fields in their correct positions
		for _, newCol := range newColumns {
			if !newCol.AutoGenerated {
				if pos, ok := te.FieldPositionMap[newCol.Name]; ok && pos < len(orderedColumns) {
					orderedColumns[pos] = ColumnInfo{
						Name:          newCol.Name,
						Type:          newCol.Type,
						AutoGenerated: false,
					}
					usedPositions[pos] = true
				}
			}
		}

		// Then fill in any remaining positions with the original columns
		origIdx := 0
		for i := range orderedColumns {
			if !usedPositions[i] {
				// Find next unused original column
				for origIdx < len(newSchema.Columns) && usedPositions[origIdx] {
					origIdx++
				}
				if origIdx < len(newSchema.Columns) {
					orderedColumns[i] = newSchema.Columns[origIdx]
					usedPositions[origIdx] = true
					origIdx++
				}
			}
		}

		newSchema.Columns = orderedColumns
		te.SchemaVersions[te.CurrentVersion] = newSchema
		return true
	}

	// Update existing schema
	updatedColumns := make([]ColumnInfo, 0, len(currentSchema.Columns))
	processedNames := make(map[string]bool)

	for _, newCol := range newColumns {
		processedNames[newCol.Name] = true
		var existingCol *ColumnInfo
		for j := range currentSchema.Columns {
			if currentSchema.Columns[j].Name == newCol.Name {
				existingCol = &currentSchema.Columns[j]
				break
			}
		}
		if existingCol != nil {
			if newCol.Type != existingCol.Type {
				loosenedType := promoteType(existingCol.Type, newCol.Type)
				if loosenedType != existingCol.Type {
					updatedColumns = append(updatedColumns, ColumnInfo{
						Name:          newCol.Name,
						Type:          loosenedType,
						AutoGenerated: true,
					})
					changed = true
				} else {
					updatedColumns = append(updatedColumns, *existingCol)
				}
			} else {
				updatedColumns = append(updatedColumns, *existingCol)
			}
		} else {
			updatedColumns = append(updatedColumns, newCol)
			changed = true
		}
	}

	for _, existingCol := range currentSchema.Columns {
		if !processedNames[existingCol.Name] {
			updatedColumns = append(updatedColumns, existingCol)
		}
	}

	currentSchema.Columns = updatedColumns
	return changed
}

// positionAlreadyMapped checks if a position is already mapped to a named field
func positionAlreadyMapped(pos int, fmap map[string]int) bool {
	for _, v := range fmap {
		if v == pos {
			return true
		}
	}
	return false
}

// RecordStructure records the schema version used for a specific record
func (te *TableEvolution) RecordStructure(recordIndex int, columns []ColumnInfo) {
	te.RecordVersionMap[recordIndex] = te.CurrentVersion
}

// GetRecordStructure returns the column structure used for a specific record
func (te *TableEvolution) GetRecordStructure(recordIndex int) []ColumnInfo {
	if version, exists := te.RecordVersionMap[recordIndex]; exists {
		if schema, ok := te.SchemaVersions[version]; ok {
			return schema.Columns
		}
	}
	return te.SchemaVersions[te.CurrentVersion].Columns
}

// GetCurrentColumns returns the columns from the current schema version
func (te *TableEvolution) GetCurrentColumns() []ColumnInfo {
	if schema, ok := te.SchemaVersions[te.CurrentVersion]; ok {
		return schema.Columns
	}
	return nil
}
