/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * json schema referenced by data in CacheableDataResult
 */
export interface YayamYamlDatabaseSchema {
  _codecs?: {
    [k: string]: unknown;
  } | null;
  _keys?: {
    [k: string]: unknown;
  } | null;
  _schemas?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z][a-zA-Z0-9]+$".
     */
    [k: string]: {
      items?: {
        properties?: {
          [k: string]: unknown;
        };
        /**
         * schema for a single row, which is an object
         */
        type?: string;
        [k: string]: unknown;
      };
      /**
       * table rows are arrays
       */
      type?: string;
      [k: string]: unknown;
    };
  };
  /**
   * This interface was referenced by `YayamYamlDatabaseSchema`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z][a-zA-Z0-9]+$".
   */
  [k: string]: any | null;
}
